language: ruby
cache: bundler
rvm:
- 2.0.0
- 2.1.0
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database metova;' -U postgres
deploy:
  provider: rubygems
  api_key:
    secure: ARM2JGEokm/TaJvIIwGgdL4s0QuMlwdVXzwtE4TwiqiSQO2yp8Eet9B0o55O3fITV2Z9UGUBF/9ymoKD2S4m/iGOARosj8q+gmgE/84fdF3glAqTtkCPsUZH8fseAH41e4XYwWkoRhwbxHBVhLn5rVGO4oJKWtFGnddacDBolFQ=
  gem:
    master: metova
  on:
    repo: metova/metova-rails
    branch: master
